### ISSUE TITLE
临时解决plasmashell狂占CPU的bug

### ISSUE THREAD

**Issue by ferstar** [ferstar/blog#20]
本子升到20.04, 顺路换成了KDE, 不过一直有个问题就是: 每次从休眠唤醒一段时间后, 桌面会变的异常卡, htop一发发现plasmashell占了近100%, 这明显不科学, google一发发现似乎是kde的陈年烂事, 没办法, 大力出奇迹~

```shell
killall plasmashell; kstart5 plasmashell; exit
```

后来发现把独显屏蔽似乎就没这个问题了, 看来还是NV显卡驱动的锅
![image](https://user-images.githubusercontent.com/2854276/81272274-db236e00-907f-11ea-99bc-f5219cbd83b1.png)

**Comment by ferstar** [comment]
另外如果发现菜单图表雪花, 也可以通过kill大法搞定, 如图
![image](https://user-images.githubusercontent.com/2854276/81284262-78869e00-9090-11ea-91a7-c13f3dc179e2.png)

**Comment by swimmingchar** [comment]
2024年的kde 6 plasmashell 表示，最近6.0.5也时不时的100%，我用的还是AMD的7735HS,都没有独显

**Comment by ferstar** [comment]
@swimmingchar 清一下 KDE 配置，也许有奇效；我升到 KDE6 倒是感觉良好，上面说的本子早卖掉了，目前是 ThinkBook 14+ AMD yes！8845H
